BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "person" (
	"id"	INTEGER NOT NULL,
	"parentsID"	INTEGER,
	"surname"	TEXT,
	"forename"	TEXT,
	"maiden_surname"	TEXT,
	"maiden_forename"	TEXT,
	"gender"	TEXT,
	"birthPlace"	INTEGER,
	"deathPlace"	INTEGER,
	"birth_year"	INTEGER,
	"birth_month"	INTEGER,
	"birth_day"	INTEGER,
	"death_year"	INTEGER,
	"death_month"	INTEGER,
	"death_day"	INTEGER,
	"death_cause"	TEXT,
	"occupation"	TEXT,
	"notes"	TEXT,
	PRIMARY KEY("id")
);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (1,23,'Budai','Tamara','','','F',15,9,'',NULL,NULL,'','','',NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (2,NULL,'Deák','Gábor',NULL,NULL,'M',1,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (3,1,'Deák','István','',NULL,'M',6,16,NULL,NULL,NULL,'','','',NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (4,1,'Deák','Péter',NULL,NULL,'M',1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (5,24,'Németh','Ágota',NULL,NULL,'F',9,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (6,25,'Szabó','Margit',NULL,NULL,'F',7,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (7,2,'Deák','Tímea',NULL,NULL,'F',18,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (8,2,'Deák','László',NULL,NULL,'M',20,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (9,2,'Deák','Flóra',NULL,NULL,'F',5,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (10,3,'Deák','Miklós',NULL,NULL,'M',12,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (11,3,'Deák','Gertrúd',NULL,NULL,'F',7,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (12,26,'Mikszáth','Viktor',NULL,NULL,'M',7,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (13,27,'Koncz','Veronika',NULL,NULL,'F',6,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (14,28,'Hermann','Csaba',NULL,NULL,'M',17,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (15,29,'Hegedűs','Berta',NULL,NULL,'F',4,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (16,30,'Törteli','Alex',NULL,NULL,'M',14,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (17,4,'Mikszáth','Kálmán',NULL,NULL,'M',7,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (18,4,'Mikszáth','Alexandra',NULL,NULL,'F',1,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (19,5,'Deák','Aurélia',NULL,NULL,'F',5,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (20,6,'Hermann','Pál',NULL,NULL,'M',2,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (21,6,'Hermann','Annamária',NULL,NULL,'F',11,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (22,6,'Hermann','Benedek',NULL,NULL,'M',2,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (23,7,'Deák','Margit',NULL,NULL,'F',8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (24,7,'Deák','Marcell',NULL,NULL,'M',20,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (25,8,'Törteli','Tamás',NULL,NULL,'M',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (26,8,'Törteli','Ignác',NULL,NULL,'M',7,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (27,8,'Törteli','Mária',NULL,NULL,'F',13,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (28,31,'Fejes','Anikó',NULL,NULL,'F',8,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (29,32,'Várady','Kristóf',NULL,NULL,'M',9,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (30,33,'Szőlőssy','Noel',NULL,NULL,'M',3,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (31,34,'Csordás','Andrea',NULL,NULL,'F',13,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (32,35,'Kondás','Milán',NULL,NULL,'M',9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (33,36,'Pásztor','Fanni',NULL,NULL,'F',18,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (34,37,'Fodrász','Imre',NULL,NULL,'M',7,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (35,38,'Vágó','Laura',NULL,NULL,'F',7,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (36,39,'Müller','Éva',NULL,NULL,'F',8,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (38,NULL,'Bogáromi','Benjámin',NULL,NULL,'M',19,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (39,10,'Várady','Konrád',NULL,NULL,'M',11,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (40,10,'Várady','Kamilla',NULL,NULL,'F',7,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (41,11,'Szőlőssy','Bertalan',NULL,NULL,'M',11,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (42,11,'Szőlőssy','Albert',NULL,NULL,'M',7,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (43,11,'Szőlőssy','Antonella',NULL,NULL,'F',14,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (44,12,'Hermann','Petra',NULL,NULL,'F',2,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (45,14,'Hermann','Herbert',NULL,NULL,'M',6,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (46,14,'Hermann','Henrietta',NULL,NULL,'F',5,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (47,15,'Fodrász','Kálmán',NULL,NULL,'M',13,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (48,15,'Fodrász','Olivér',NULL,NULL,'M',11,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (49,15,'Fodrász','Márta',NULL,NULL,'F',4,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (50,15,'Fodrász','Vilma',NULL,NULL,'F',3,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (51,15,'Fodrász','Vilmos',NULL,NULL,'M',13,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (52,15,'Fodrász','Vanessza',NULL,NULL,'F',1,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (53,15,'Fodrász','Viktória',NULL,NULL,'F',7,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (54,15,'Fodrász','Olga',NULL,NULL,'F',19,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (55,15,'Fodrász','Károly',NULL,NULL,'M',3,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (56,40,'Bálint','Kelemen',NULL,NULL,'M',15,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (57,20,'Bálint','Tamara',NULL,NULL,'F',18,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (58,20,'Bálint','Bálint',NULL,NULL,'M',12,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (59,18,'Törteli','Elemér',NULL,NULL,'M',13,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (60,18,'Törteli','Márk',NULL,NULL,'M',7,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (61,41,'Keserű','Krisztián',NULL,NULL,'M',4,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (62,21,'Keserű','Krisztián',NULL,NULL,'M',18,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (63,21,'Keserű','Krisztina',NULL,NULL,'F',6,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (64,17,'Törteli','Jeremiás',NULL,NULL,'M',12,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (65,17,'Törteli','Ezékiel',NULL,NULL,'M',10,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (66,42,'Takács','Urszula',NULL,NULL,'F',12,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (67,18,'Törteli','Ézsaiás',NULL,NULL,'M',15,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (68,18,'Törteli','Dániel',NULL,NULL,'M',14,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (69,13,'Kondás','János',NULL,NULL,'M',15,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (70,NULL,'Szép','Erzsébet',NULL,NULL,'F',12,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (71,NULL,'Németh','Edvin',NULL,NULL,'M',18,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (72,NULL,'Horváth','Jázmin',NULL,NULL,'F',9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (73,NULL,'Szabó','Menyhért',NULL,NULL,'M',14,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (74,NULL,'Varga','Zselyke',NULL,NULL,'F',14,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (75,NULL,'Mikszáth','Sámuel',NULL,NULL,'M',3,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (76,NULL,'Bogdán','Magdolna',NULL,NULL,'F',20,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (77,NULL,'Koncz','Bernát',NULL,NULL,'M',20,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (78,NULL,'Hegedűs','Csilla',NULL,NULL,'F',15,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (79,NULL,'Hermann','Róbert',NULL,NULL,'M',18,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (80,NULL,'Csonka','Andrea',NULL,NULL,'F',8,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (81,NULL,'Hegedűs','Hunor',NULL,NULL,'M',1,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (82,NULL,'Tóth','Szabina',NULL,NULL,'F',12,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (83,NULL,'Törteli','Illés',NULL,NULL,'M',8,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (84,NULL,'Müller','Cecília',NULL,NULL,'F',10,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (85,NULL,'Fejes','Álmos',NULL,NULL,'M',2,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (86,NULL,'Lukács','Bianka',NULL,NULL,'F',12,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (87,NULL,'Várady','Előd',NULL,NULL,'M',18,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (88,NULL,'Ultra','Ibolya',NULL,NULL,'F',7,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (89,NULL,'Szőlőssy','Ond',NULL,NULL,'M',10,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (90,NULL,'Halász','Ágota',NULL,NULL,'F',19,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (91,NULL,'Csordás','Kond',NULL,NULL,'M',10,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (92,NULL,'Orosz','Hanga',NULL,NULL,'F',14,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (93,NULL,'Kondás','Tas',NULL,NULL,'M',6,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (94,NULL,'Papp','Kitti',NULL,NULL,'F',15,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (95,NULL,'Pásztor','Huba',NULL,NULL,'M',6,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (96,NULL,'Fodor','Réka',NULL,NULL,'F',14,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (97,NULL,'Fodrász','Teodor',NULL,NULL,'M',6,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (98,NULL,'Lengyel','Hajnalka',NULL,NULL,'F',20,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (99,NULL,'Vágó','Ferenc',NULL,NULL,'M',3,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (100,NULL,'Kelemen','Dóra',NULL,NULL,'F',3,'',NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (101,NULL,'Müller','Jakab',NULL,NULL,'M',7,'',NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (102,NULL,'Szekeres','Eleonóra',NULL,NULL,'F',6,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (103,NULL,'Bálint','Károly',NULL,NULL,'M',1,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (104,NULL,'Orsós','Dorottya',NULL,NULL,'F',20,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (105,NULL,'Keserű','Töhötöm',NULL,NULL,'M',14,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (106,NULL,'Balázs','Klára',NULL,NULL,'F',11,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (107,NULL,'Takács','Milán',NULL,NULL,'M',7,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (108,NULL,'Fazekas','Gizella',NULL,NULL,'F',3,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (109,24,'Németh','Fanni',NULL,NULL,'F',20,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (110,24,'Németh','Teodor',NULL,NULL,'M',15,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (111,24,'Németh','Gyula',NULL,NULL,'M',18,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (112,25,'Szabó','Júlia',NULL,NULL,'F',12,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (113,25,'Szabó','Bence',NULL,NULL,'M',13,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (114,27,'Koncz','Eszter',NULL,NULL,'F',7,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (115,27,'Koncz','Tibor',NULL,NULL,'M',4,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (116,27,'Koncz','Andrea',NULL,NULL,'F',18,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (117,27,'Koncz','Ármin',NULL,NULL,'M',6,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (118,27,'Koncz','Arnold',NULL,NULL,'M',12,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (119,28,'Hermann','Nikoletta',NULL,NULL,'F',10,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (120,29,'Hegedűs','Nadin',NULL,NULL,'M',12,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (121,29,'Hegedűs','Atlasz',NULL,NULL,'M',15,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (122,30,'Törteli','Ametiszt',NULL,NULL,'M',14,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (123,31,'Fejes','Péter',NULL,NULL,'M',15,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (124,33,'Szőlőssy','Csaba',NULL,NULL,'M',12,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (125,33,'Szőlőssy','Attila',NULL,NULL,'M',18,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (126,33,'Szőlőssy','Anatólia',NULL,NULL,'F',9,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (127,33,'Szőlőssy','Zsófia',NULL,NULL,'F',14,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (128,33,'Szőlőssy','Aurélia',NULL,NULL,'F',14,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (129,33,'Szőlőssy','Anikó',NULL,NULL,'F',3,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (130,34,'Csordás','Mihály',NULL,NULL,'M',20,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (131,34,'Csordás','Csanád',NULL,NULL,'M',20,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (132,35,'Kondás','Lotti',NULL,NULL,'F',15,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (133,35,'Kondás','Adél',NULL,NULL,'F',18,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (134,35,'Kondás','Györgyi',NULL,NULL,'F',8,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (135,36,'Pásztor','Ilma',NULL,NULL,'F',1,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (136,36,'Pásztor','Pandóra',NULL,NULL,'F',12,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (137,36,'Pásztor','György',NULL,NULL,'M',8,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (138,37,'Fodrász','Jakab',NULL,NULL,'M',10,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (139,38,'Vágó','Ágnes',NULL,NULL,'F',2,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (140,38,'Vágó','Benjámin',NULL,NULL,'M',12,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (141,38,'Vágó','Baltazár',NULL,NULL,'M',18,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (142,38,'Vágó','Torda',NULL,NULL,'M',7,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (143,39,'Müller','Cecília',NULL,NULL,'F',10,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (144,39,'Müller','Hanga',NULL,NULL,'F',19,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (145,40,'Bálint','Hajnal',NULL,NULL,'F',10,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (146,42,'Takács','Béni',NULL,NULL,'M',14,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
INSERT INTO "person" ("id","parentsID","surname","forename","maiden_surname","maiden_forename","gender","birthPlace","deathPlace","birth_year","birth_month","birth_day","death_year","death_month","death_day","death_cause","occupation","notes") VALUES (147,42,'Takács','Miklós',NULL,NULL,'M',6,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL);
COMMIT;
